# Generated by Django 4.0.4 on 2022-05-25 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='coworkers',
            field=models.ManyToManyField(related_name='coworked_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
